# NumPy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful capabilities from linear algebra, statistics, calculus, random number, etc.
* operates efficiently using vectorized implementations of the algorithms

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

We start loading the package, using the alias `np`. In order to do that, `numpy` must be properly installed.

In [1]:
import numpy as np

## Arrays

Arrays are the main object in NumPy, and they consist in **homogeneous multidimensional arrays**, or tensors. It consists in a collection of elements (usually numbers), all of the same type (homogeneous) and indexed by a tuple of positive integers. 

Dimensions are called **axes**, and the number of axes is the **rank**.

For example, let us consider the coordinates of a point in the space $\mathbb{R}^3$, it consists in an array of rank 1 (only one axis), with length 3.

`[1.,3.,2.]`

We can also consider a matrix of integer values, or rank 2 array, with 2 rows and 3 columns.

`[[ 1, 0, 0],
 [ 0, 1, 2]]`
 
 The element in the position `(1,2)` is 2. **Indices start at 0.**


## Creating arrays

The simplest way of creating an `array` is to convert a Python's list into an array, the type of the elements will be deduced automatically.

This is done with the method `np.array()`.

In [3]:
mylist = [1, 2, 3]
x = np.array(mylist)

In [4]:
x

array([1, 2, 3])

Each array has two attributes:
* `dtype`: the type of the elements. It is usually int or float, followed by the precision.
* `shape`: the dimensions of the array.

In [5]:
x.dtype

dtype('int64')

In [6]:
x.shape

(3,)

In [7]:
x = np.array([1, 2, 3.5])
x

array([1. , 2. , 3.5])

In [8]:
x.dtype

dtype('float64')

<br>
To create  higher rank arrays, you can transform a list of lists (of lists of ...) into an `array`.

In [9]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [10]:
m.shape

(2, 3)

<br>
Arrays can be created using predefined constructors, without having to state all elements. Let us explore some options.

`arange` returns evenly spaced values within a given interval, indicating the step. As with `range`, it spans the **semi-open** set [start, stop).

In [10]:
x = np.arange(0, 30, 2.3) # de 0 a 30 contando de 2.3 en 2.3
x

array([ 0. ,  2.3,  4.6,  6.9,  9.2, 11.5, 13.8, 16.1, 18.4, 20.7, 23. ,
       25.3, 27.6, 29.9])

`linspace` returns evenly spaced numbers over a specified interval, indicating the number of points. By default it **includes the endpoint**.

In [11]:
x = np.linspace(0, 30, 9) # 9 números equiespaciados en [0, 30]
x

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  , 18.75, 22.5 , 26.25, 30.  ])

`zeros` y `ones` create arrays with all its elements 0 or 1 respectively.

In [14]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(11,dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [14]:
3*np.ones([2,2,3])

array([[[3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.]]])

`eye` created an identity matrix, and `diag` and diagonal matrix.

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.diag([6,8,9])

array([[6, 0, 0],
       [0, 8, 0],
       [0, 0, 9]])

## Combining  arrays

In [18]:
x = np.ones([2, 3])
x

array([[1., 1., 1.],
       [1., 1., 1.]])

`vstack` stacks arrays in sequence vertically (row wise), it is the same as a concatenation along the first axis (index 0).

In [21]:
y = np.vstack([x, 2*x])
print('shape = ',y.shape)
y

shape =  (4, 3)


array([[1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]])

`hstack` stacks arrays in sequence horizontally (column wise), it is the same as a concatenation along the second axis (index 1).

In [23]:
y = np.hstack([x, 2*x, 3*x])
print('shape = ',y.shape)
y

shape =  (2, 9)


array([[1., 1., 1., 2., 2., 2., 3., 3., 3.],
       [1., 1., 1., 2., 2., 2., 3., 3., 3.]])

## Operations with arrays

`reshape` gives a new shape to an array without changing its data.
In the example you can see that it starts filling along the last axis (in this case, the one of length 5).

In [25]:
x = np.arange(0, 15)
x = np.reshape(x,[3,5]) # You can also use x.reshape([3,5])
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Given an array, we can read and modify each element.

In [26]:
x[0,1] = 100*x[0,1]
x

array([[  0, 100,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

We can specify the order of the filling, it can be C like or F (Fortran) like.

In [30]:
x = np.arange(0, 15)
x = np.reshape(x,[3,5],order='F') # You can also use x.reshape([3,5],order='F')
x

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

You can easily transpose an array with the attribute `.T` or with the method `transpose()`.

In [37]:
print('Original\n',x,'\nTransposed\n',x.T)

Original
 [[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]] 
Transposed
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]



**Warning:** transposing is not the same as reshaping alternating the dimensions.

In [39]:
x = np.arange(0,15).reshape([3,5]).T
y = np.arange(0, 15).reshape([5,3])
print(x)
print(y)
print(x==y)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ True False False]
 [False False False]
 [False  True False]
 [False False False]
 [False False  True]]


You can also transpose arrays with rank higher than 2.

In [41]:
x = np.arange(0,24).reshape([2,3,4])
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [44]:
print('Transposed shape = ',x.T.shape, '\nTransposed array')
print(x.T)

Transposed shape =  (4, 3, 2) 
Transposed array
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


You can use Python's mathematical operators to perform **element-wise** operations on arrays.

`+`, `-`, `*`, `/` , `//` , `%` and `**` work as expected.

In [46]:
x = np.arange(1,5)
y = x + x
print(x,'+',x,'=',y)

[1 2 3 4] + [1 2 3 4] = [2 4 6 8]


In [47]:
x = np.arange(1,5)
y = x - x
print(x,'-',x,'=',y)

[1 2 3 4] - [1 2 3 4] = [0 0 0 0]


In [48]:
x = np.arange(1,5)
y = x * x
print(x,'*',x,'=',y)

[1 2 3 4] * [1 2 3 4] = [ 1  4  9 16]


In [49]:
x = np.arange(1,5)
y = x / x
print(x,'/',x,'=',y)

[1 2 3 4] / [1 2 3 4] = [1. 1. 1. 1.]


In [54]:
x = np.arange(1,5)
y = np.arange(11,15)
z = y // x
print(y,'//',x,'=',z)

[11 12 13 14] / [1 2 3 4] = [11  6  4  3]


In [55]:
x = np.arange(1,5)
y = np.arange(11,15)
z = y % x
print(y,'%',x,'=',z)

[11 12 13 14] % [1 2 3 4] = [0 0 1 2]


In [50]:
x = np.arange(1,5)
y = x**2
print(x,'**2','=',y)

[1 2 3 4] **2 = [ 1  4  9 16]


`dot` performs scalar product in the case of 1-D arrays and matrix multiplication for 2-D arrays.

In [58]:
x = np.arange(16).reshape(4,4)
y = np.eye(4) # identity matrix
z = np.dot(x,y) # Should be the same as x
print(x == z) # They coincide

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [60]:
x = np.arange(16).reshape(4,4)
y = np.eye(4) # identity matrix
z = x * y # This is different, since it is element-wise multiplication
print(x == z) # They do not coincide

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


## Iterating over arrays

In [145]:
## We can generate arrays following a probability distribution with np.random
matrix = np.random.uniform(0, 1, (4,3)) 
print(matrix)

[[0.59983692 0.17107237 0.80007219]
 [0.37827457 0.28482984 0.82535253]
 [0.19976442 0.17179669 0.69350376]
 [0.25323448 0.79032555 0.91211017]]


Iterate over indices

In [147]:
for i in range(len(matrix)):
    print(matrix[i])

[0.59983692 0.17107237 0.80007219]
[0.37827457 0.28482984 0.82535253]
[0.19976442 0.17179669 0.69350376]
[0.25323448 0.79032555 0.91211017]


Iterate over rows

In [146]:
for row in matrix:
    print(row)

[0.59983692 0.17107237 0.80007219]
[0.37827457 0.28482984 0.82535253]
[0.19976442 0.17179669 0.69350376]
[0.25323448 0.79032555 0.91211017]


Iterate over indices and rows

In [149]:
for i, row in enumerate(matrix):
    print('row', i, 'is', row)

row 0 is [0.59983692 0.17107237 0.80007219]
row 1 is [0.37827457 0.28482984 0.82535253]
row 2 is [0.19976442 0.17179669 0.69350376]
row 3 is [0.25323448 0.79032555 0.91211017]


You can nest the iterators

In [150]:
for row in matrix:
    for el in row:
        print(el)

0.599836922888499
0.17107236774206558
0.8000721869623799
0.3782745679758731
0.28482984047840587
0.8253525259806724
0.19976441533524425
0.17179668733279807
0.6935037553269237
0.2532344837943472
0.7903255489497353
0.9121101742532558


In [157]:
[print(el)  for row in matrix for el in row]

0.599836922888499
0.17107236774206558
0.8000721869623799
0.3782745679758731
0.28482984047840587
0.8253525259806724
0.19976441533524425
0.17179668733279807
0.6935037553269237
0.2532344837943472
0.7903255489497353
0.9121101742532558


[None, None, None, None, None, None, None, None, None, None, None, None]

## Mathematical functions

NumPy has implemented many of the usual mathematical functions, and they are applied element-wise to an array. Some of them are `sin`, `cos`, `exp`, `sqrt`, `log`. Also, you can access the value of $\pi$ with `np.pi`.

You can find a complete list in 

https://docs.scipy.org/doc/numpy/reference/routines.math.html

### Element-wise mathematical function

In [67]:
np.sin(np.linspace(0,np.pi,5))**2

array([0.00000000e+00, 5.00000000e-01, 1.00000000e+00, 5.00000000e-01,
       1.49975978e-32])

In [73]:
x = np.linspace(1,10,5)
print('x =',x)
xlog = np.log(x)
print('log(x) =',xlog)
xexp = np.exp(x)
print('exp(x) =',xexp)

x = [ 1.    3.25  5.5   7.75 10.  ]
log(x) = [0.         1.178655   1.70474809 2.04769284 2.30258509]
exp(x) = [2.71828183e+00 2.57903399e+01 2.44691932e+02 2.32157241e+03
 2.20264658e+04]


### <span style="color:red">**Exercise**</span> 

Create a function that obtains the cosine of the angle between two vectors.

$$ \cos \theta = \frac{\langle v_1, v_2 \rangle}{||v_1|| ||v_2||} $$

where $|| v ||$ is the norm of v, which can be expressed as $\sqrt{\langle v, v \rangle}$

### <span style="color:red">**Exercise**</span> 

Using two nested for loops, implement a function to calculate the mean value of the elements of a matrix.

### Mathematical functions on axes of the array

NumPy has plenty of functions to operate on `arrays`. To calculate the sum of elements `sum`, or their product `prod`. Also statistical ones like the mean `mean` and the standard deviation `std`.

You can usually specify along which `axis` to perform the operation with the `axis` option, if it is not specified, the array is flattened.

In general, with the method `np.apply_along_axis(function, axis, array)` we can apply an arbitrary function slicing along a given `axis`.

In [143]:
def arggmax(x):
    return np.argmax(x)
axis = 0
matrix = np.array([[1,3,5,7],[0,2,4,8]])
print(matrix)
print('argmax over axis',axis)
print(np.apply_along_axis(arggmax, axis, matrix))
print(matrix.argmax(axis = axis))

[[1 3 5 7]
 [0 2 4 8]]
argmax over axis 0
[0 0 0 1]
[0 0 0 1]


In [106]:
vector = np.array([-4, -2, 1, 3, 5])
matrix = np.array([[1,3,5,7],[0,2,4,8]])
print('vector')
print(vector)
print('matrix')
print(matrix)

vector
[-4 -2  1  3  5]
matrix
[[1 3 5 7]
 [0 2 4 8]]


In [107]:
print('sum')
print('vector =', vector.sum())
print('matrix =', matrix.sum())
print('matrix (over rows)=', matrix.sum(axis=0))
print('matrix (over columns)=', matrix.sum(axis=1))

sum
vector = 3
matrix = 30
matrix (over rows)= [ 1  5  9 15]
matrix (over columns)= [16 14]


In [108]:
print('product')
print('vector =', vector.prod())
print('matrix =', matrix.prod())
print('matrix (over rows)=', matrix.prod(axis=0))
print('matrix (over columns)=', matrix.prod(axis=1))

product
vector = 120
matrix = 0
matrix (over rows)= [ 0  6 20 56]
matrix (over columns)= [105   0]


In [109]:
print('max')
print('vector =', vector.max())
print('matrix =', matrix.max())
print('matrix (over rows)=', matrix.max(axis=0))
print('matrix (over columns)=', matrix.max(axis=1))

max
vector = 5
matrix = 8
matrix (over rows)= [1 3 5 8]
matrix (over columns)= [7 8]


In [110]:
print('min')
print('vector =', vector.min())
print('matrix =', matrix.min())
print('matrix (over rows)=', matrix.min(axis=0))
print('matrix (over columns)=', matrix.min(axis=1))

min
vector = -4
matrix = 0
matrix (over rows)= [0 2 4 7]
matrix (over columns)= [1 0]


In [111]:
print('mean')
print('vector =', vector.mean())
print('matrix =', matrix.mean())
print('matrix (over rows)=', matrix.mean(axis=0))
print('matrix (over columns)=', matrix.mean(axis=1))

mean
vector = 0.6
matrix = 3.75
matrix (over rows)= [0.5 2.5 4.5 7.5]
matrix (over columns)= [4.  3.5]


In [112]:
print('standard deviation')
print('vector =', vector.std())
print('matrix =', matrix.std())
print('matrix (over rows)=', matrix.std(axis=0))
print('matrix (over columns)=', matrix.std(axis=1))

standard deviation
vector = 3.2619012860600183
matrix = 2.6339134382131846
matrix (over rows)= [0.5 0.5 0.5 0.5]
matrix (over columns)= [2.23606798 2.95803989]


In [117]:
print('argmax')
print('vector =', vector.argmax())
print('matrix =', matrix.argmax())
print('matrix (over rows)=', matrix.argmax(axis=0))
print('matrix (over columns)=', matrix.argmax(axis=1))

argmax
vector = 4
matrix = 7
matrix (over rows)= [0 0 0 1]
matrix (over columns)= [3 3]


In [124]:
print('argmin')
print('vector =', vector.argmin())
print('matrix =', matrix.argmin())
print('matrix (over rows)=', matrix.argmin(axis=0))
print('matrix (over columns)=', matrix.argmin(axis=1))

argmin
vector = 0
matrix = 4
matrix (over rows)= [1 1 1 0]
matrix (over columns)= [0 0]


### <span style="color:red">**Exercise**</span> 

Given a matrix M, built a vector wich i-th element is the product of the sum of the elements of the i-th row of M times the product of the elements of the i-th row of M. 

Can you do it with one line of code? **Hint:** Use lambda functions.

In [1]:
M = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(M)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


## Indexing/Slicing

Similarly to lists, you can index arrays using square brackets `[]`.

You can also sliced over with expressions like `[start:stop:step]`.

In [159]:
vector = np.arange(20)
print(vector)
vector[0], vector[4], vector[-1]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


(0, 4, 19)

In [160]:
vector[0:5:2]

array([0, 2, 4])

In the case the rank is larger than 1

In [161]:
matrix = np.arange(34)
matrix.resize((6, 6))
matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33,  0,  0]])

In [162]:
matrix[2, 2]

14

In [163]:
matrix[1, 3:6]

array([ 9, 10, 11])

We can extract all the rows of `matrix` up to the 2 (not including it) and all columns up to the last one (not including it).

In [165]:
matrix[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

Selecting only one row

In [166]:
matrix[-1, :]

array([30, 31, 32, 33,  0,  0])

Selecting only one column 

In [167]:
matrix[:, 0]

array([ 0,  6, 12, 18, 24, 30])

**Conditional indexing** can also be applied!

In [170]:
matrix[matrix % 2 ==0] # This selects only the even elements in matrix

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        0,  0])

### <span style="color:red">**Exercise**</span> 

First, select the first column of the given matrix `A`, and save it in the variable `v`.
Substitute the elements in `v` that are null for $7$.

Calculate the matrix product `A` $\cdot$ `v`. 

Result = `[43,  0, 98]`

**Warning:** Be careful with the pointers.

In [175]:
A = np.array([[1,2,4],[0,0,0],[0,6,8]])

## Vectorization and broadcasting

If it is possible, explicit `for` loops should be avoided in Python, since it is faster to use vectorized functions (i.e., functions that apply directly to vectors/tensors).

Let us show that with an example. We will calculate the mean value of a list of numbers satisfying a condition.

In [180]:
vector = np.random.randn(1000000) # 1 million numbers sampled from a normal distribution

In [183]:
%%timeit -n1
s = 0
# We use a for loop to access the elements
for n in vector:  
    if n>0:
        s += n
mean = s/len(vector)
mean

296 ms ± 12 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [184]:
%%timeit -n1
# We apply the mean method to the vector directly, using the mask with the condition.
mean = vector[vector>0].mean()  
mean

11.2 ms ± 2.09 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


**Broadcasting** allows universal functions to deal in a meaningful way with inputs that do not have exactly the same shape.

The first rule of broadcasting is that if all input arrays **do not have the same number of dimensions**, a “1” will be repeatedly **prepended** to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

The second rule of broadcasting ensures that **arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension**. The value of the array element is assumed to be the same along that dimension for the “broadcast” array.

After application of the broadcasting rules, the sizes of all arrays must match. More details can be found in

https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

The simplest broadcasting example occurs when an array and a scalar value are combined in an operation.

In [187]:
scalar = 3.
matrix = np.linspace(0,15,16).reshape([4,4])
matrix / scalar

array([[0.        , 0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        , 2.33333333],
       [2.66666667, 3.        , 3.33333333, 3.66666667],
       [4.        , 4.33333333, 4.66666667, 5.        ]])

A slightly more complicated example occurs when combining a matrix and a vector.

In [202]:
matrix = np.linspace(0,9,10).reshape([2,-1])
# We need to transform the vector into a "column" vector
vector = np.array([0,2]).reshape([2,1])
# vector = np.array([0,2])[:,np.newaxis]
print('matrix\n',matrix)
print('vector\n',vector)
print('matrix * vector\n',vector * matrix)

matrix
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
vector
 [[0]
 [2]]
matrix * vector
 [[ 0.  0.  0.  0.  0.]
 [10. 12. 14. 16. 18.]]


We can broadcast in the other axis, just using a vector with length equal to the first axis (columns).

In [204]:
matrix = np.linspace(0,9,10).reshape([2,-1])
# We need to transform the vector into a "column" vector
vector = np.array([0,1,2,3,4])
# vector = np.array([0,2])[:,np.newaxis]
print('matrix\n',matrix)
print('vector\n',vector)
print('matrix * vector\n',vector * matrix)

matrix
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
vector
 [0 1 2 3 4]
matrix * vector
 [[ 0.  1.  4.  9. 16.]
 [ 0.  6. 14. 24. 36.]]


### <span style="color:red">**Exercise**</span> 

Using two given vectors `v1` and `v2`. Build a matrix `A` with elements `A[i][j] = v1[i]**v2[j]`.
Try to code it in one line using broadcasting.

In [210]:
v1 = np.array([10,20,30,40,50])
v2 = np.array([0,1,2,3])

### <span style="color:red">**Exercise**</span> 

Given an array `matrix` having the sampling of 5 heads or tails (head = 1, tails = 0) experiments of 100 trials each. Our goal is to determine if the coin is fair.
Create two vectors `means` and `sigmas_mean`, containing the mean values for each experiment and the standard deviation of the mean $\sigma_{\text{mean}} = \frac{\sigma}{\sqrt{n}}$.

Print, for each experiment, the $95\%$ confidence interval of the mean with the following string:

'Experiment `i` . CI (95%) = [ `mean - 1.96 sigma_mean` , `mean + 1.96 sigma_mean` ]' ,

being `i` the number of the experiment, `mean` the mean of the experiment and `sigma_mean` the standard deviation of the mean of the experiment.

Finally, observe that the CI shrinks when increasing the number of trials per experiment.

In [238]:
matrix = np.random.randint(0,2, (5,100))

## Extra: EinSum

Using the einsum function, we can specify operations on NumPy arrays using the Einstein summation convention.

It can often outperform familiar array functions in terms of speed and memory efficiency, thanks to its expressive power and smart loops. 

We can start practicing with a matrix. Let us get the trace, the diagonal and the total sum.

In [74]:
A = np.array(np.arange(16)).reshape([4,4])
print('A\n-------\n',A)
print('\nTrace\n-------')
print(np.einsum('ii -> ',A))
print('\nDiagonal\n-------')
print(np.einsum('ii -> i',A))
print('\nSum of all elements\n-------')
print(np.einsum('ij -> ',A))

A
-------
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Trace
-------
30

Diagonal
-------
[ 0  5 10 15]

Sum of all elements
-------
120


We can easily do matrix multiplication in this setting.

In [75]:
A = np.array(np.arange(15)).reshape([5,3])
print('A\n-------\n',A)
B = np.array(np.arange(12)).reshape([3,4])
print('B\n-------\n',B)
print('A x B\n-------')
print(np.einsum('ij,jl -> il',A,B))

A
-------
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
B
-------
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A x B
-------
[[ 20  23  26  29]
 [ 56  68  80  92]
 [ 92 113 134 155]
 [128 158 188 218]
 [164 203 242 281]]


Compute the scalar product or build a matrix from the outer product of two vectors.

In [69]:
v1 = 10*  np.array([1,2,3,4,5])
print('v1\n-------\n',v1)
v2 = np.array([0,1,2,3,4])
print('v2\n-------\n',v2)
print('Scalar product\n------')
print( np.einsum('i,i ->',v1,v2)  )
print('Outer product\n------')
print( np.einsum('i,j -> i j',v1,v2)  )
print('Outer product (transposed) \n------')
print( np.einsum('i,j -> j i',v1,v2)  )

v1
-------
 [10 20 30 40 50]
v2
-------
 [0 1 2 3 4]
Scalar product
------
400
Outer product
------
[[  0  10  20  30  40]
 [  0  20  40  60  80]
 [  0  30  60  90 120]
 [  0  40  80 120 160]
 [  0  50 100 150 200]]
Outer product (transposed) 
------
[[  0   0   0   0   0]
 [ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]]


Let us go to another example, involving rank 1 and rank 2 tensors.

As we explained before, we can multiply each row of `B` with each value of `A` using broadcasting, but we can do the same contracting indices. Also, we can keep track of the execution time of the calculation.

In [77]:
A = np.array([0, 1, 2])
print('A\n-------\n',A)
B = np.array(np.arange(12)).reshape([3,4])
print('B\n-------\n',B)

A
-------
 [0 1 2]
B
-------
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [78]:
%timeit A.reshape((-1,1))*B
print(A.reshape((-1,1))*B)

2.11 µs ± 59 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]]


In [79]:
%timeit np.einsum('i,ij->ij',A,B)
print(np.einsum('i,ij->ij',A,B))

2.34 µs ± 144 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]]


Now, after that operation, we can sum along the first axis (keeping 3 rows).

In [80]:
%timeit np.sum(A.reshape((-1,1))*B,axis=1)
print(np.sum(A.reshape((-1,1))*B,axis=1))

7.69 µs ± 237 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
[ 0 22 76]


In [81]:
%timeit np.einsum('i,ij->i',A,B)
print(np.einsum('i,ij->i',A,B))

2.34 µs ± 105 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
[ 0 22 76]


Or even sum all the values of the resulting matrix

In [82]:
%timeit np.sum(A.reshape((-1,1))*B)
print(np.sum(A.reshape((-1,1))*B))

7.76 µs ± 440 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
98


In [83]:
%timeit np.einsum('i,ij->',A,B)
print(np.einsum('i,ij->',A,B))

2.14 µs ± 91.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
98


Let us now create a tensor of rank 3, of shape (6,2,5) and calculate the trace of the six 5x5 matrices.

In [55]:
C = np.array(range(150)).reshape((6,5,5))

In [84]:
%timeit  np.einsum('i j j  -> i ',C)
print(np.einsum('i j j  -> i ',C))

2.11 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
[ 60 185 310 435 560 685]


In [85]:
%timeit  np.trace(C,axis1=1,axis2=2)
print(np.trace(C,axis1=1,axis2=2))

4.78 µs ± 99.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
[ 60 185 310 435 560 685]


### <span style="color:red">**Exercise**</span> 

Consider the large vector v defined below, and calculate v to the third power using three different methods. Compare the execution time of them.

In [93]:
v = np.random.normal(size = int(10e7))